//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kapustinRPMBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirfloatFlightsInfoTable
    {
        public int FlightNumber { get; set; }
        public string Destination { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public int AvailableSeatsCount { get; set; }
        public string AircraftType { get; set; }
        public int Capacity { get; set; }
    }
}
